### ISSUE TITLE
Error while rendering plone contectactions appeared on the portlet.

### ISSUE THREAD

**Issue by ghost** [Sinar/sinarngo.project#2]
![screen shot 2015-04-30 at 12 58 19 pm](https://cloud.githubusercontent.com/assets/11497391/7409554/cf1f55dc-ef59-11e4-91e5-492acf5f7c6b.png)

I get this issue, when I set a page as default content view.

**Comment by kaerumy** [comment]
But was because dexterity multilingual behaviour was not installed, resulting in dexterity folders not being able to display translation dropdown (hence error).
